package apt3040_final_project;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class budget_Allocation extends javax.swing.JFrame {

    /**
     * Creates new form budget_Allocation
     */
    public budget_Allocation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        department_input = new javax.swing.JTextField();
        amount_input = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setText("Budget Allocation");

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setText("Department");

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setText("Amount");

        department_input.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        department_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department_inputActionPerformed(evt);
            }
        });

        amount_input.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        amount_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_inputActionPerformed(evt);
            }
        });

        submit.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText(" Main Menu ");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(amount_input))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addComponent(department_input, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(submit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(department_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amount_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void department_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_department_inputActionPerformed

    private void amount_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_inputActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // declare an ArrayList to dynamically store department names
        ArrayList<String> Departments = new ArrayList<>();

        // db credentials
        String url = "jdbc:mysql://localhost:3306/employee_expenses";
        String uname = "APT_final_project";
        String pass = "kfc4life8";

        // connection object
        Connection con = null;
        try {
            // register JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // establish db connection
            con = DriverManager.getConnection(url, uname, pass);

            // instuction to update existing record in db (option 3)
            String sqlUpdateBudget = "UPDATE budget_management SET Budget = Budget + ? WHERE Department = ?";

            // create a prepared statement object to update budget records (option 3)
            PreparedStatement psUpdate = con.prepareStatement(sqlUpdateBudget);

            // create statement objects for executing department SQL queries
            String sqlQueryDept = "SELECT Department FROM budget_management";
            Statement st1 = con.createStatement();
            // exexuting query for existing departments and store the result in a ResultSet
            ResultSet resDept = st1.executeQuery(sqlQueryDept);
            // Iterate through result set and save Department data in arrayList
            while (resDept.next()) {
                String dept = resDept.getString("Department");
                Departments.add(dept); // add element to ArrayList
            }

            String dept;
            float amount;

            // input department and check its existence
            dept = department_input.getText();
            dept = existsDept(dept, Departments, this);
            if (dept == null) {
                department_input.setText("");
                department_input.requestFocus();
                return;
            }

            if (isFloat(amount_input.getText())) {
                amount = Float.parseFloat(amount_input.getText());
            } else {
                JOptionPane.showMessageDialog(this, "\nInvalid Amount!!!");
                amount_input.setText("");
                amount_input.requestFocus();
                return;
            }

            // set update parameters
            psUpdate.setFloat(1, amount);
            psUpdate.setString(2, dept);

            // execute the update operation
            int update = psUpdate.executeUpdate();

            // check if update was successful
            if (update > 0) {
                JOptionPane.showMessageDialog(this, "\nDepartment's budget has been increased successfully");
                // reset form
                department_input.setText("");
                amount_input.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "\nFailed to update budget!!!");
            }
        } catch (SQLException | ClassNotFoundException se) {
            // handle errors for JDBC
            se.printStackTrace();
            // display error to user
            JOptionPane.showMessageDialog(null, "SQL Exception occurred: " + se.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Finally block used to close resources
            try {
                if (con != null) {
                    con.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
                // display error to user
                JOptionPane.showMessageDialog(null, "SQL Exception occurred: " + se.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainMenu mm = new MainMenu();
        dispose();
        mm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(budget_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new budget_Allocation().setVisible(true);
        });
    }

    // checks if Department exists in DB
    public static String existsDept(String dept, ArrayList<String> Departments, JFrame parentComp) {
        String realLabel = null;
        for (String check : Departments) {
            if (dept.toLowerCase().strip().equals(check.toLowerCase())) {
                realLabel = check;
                break;
            }
        }
        if (realLabel == null) {
            JOptionPane.showMessageDialog(parentComp, "ERROR:\n...Department does not exist!!");
        }
        return realLabel;
    }

    // checks if amount field is actually a float number
    public static boolean isFloat(String txt) {
        try {
            // Use regex to check if the input contains only digits and optional decimal point
            if (txt.matches("\\d*\\.?\\d*")) {
                // If input is valid, parse it as a float
                return true;
            }
        } catch (NumberFormatException e) {
            return false;
        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_input;
    private javax.swing.JTextField department_input;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
